version: '3.4'
services:

  front-prod:
    image: slimBA1996/repository_front:latest
    container_name: container-front-prod
    depends_on:
      - rest-prod
    ports:
      - 80:80

  rest-prod:
    image: slimBA1996/repository_back:latest
    container_name: container-rest-prod
    depends_on:
      - db-prod
    ports:
      - 8080:8080

  db-prod:
    image: mongo
    container_name: container-db-prod
    ports:
      - 8081:8081


