version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo-container
    volumes:
      - mymongo-data:/data/db
    restart: always
    ports:
      - 27017:27017
volumes:
  mymongo-data: